  
tokens:
//  root_dir = '[a-zA-Z]:\/'
//  http_scheme = 'http:\/\/'
//  ftp_scheme = 'ftp:\/\/'
//  file_scheme = 'file:\/\/'
//  file_scheme_slash = 'file:\/\/' 
//  port_number = '[0-9]+'
//  path_id = '[^/ \t\r\n?#,$)]+'
//  question_mark = '\?'
//  sharp = '#'
//  amp = '&'
  
types:
  'root_dir': char  
  'path_id': String
  'port_number': int

productions:
  expr +=  uri   { expr_uri } 
        ;
       
  uri = absolute_uri   { uri_absolute }
      | relative_uri   { uri_relative }
      ;
      
  absolute_uri = scheme host port? absolute_path uri_query? fragment?   { absolute_uri }
               ;
  
  scheme = 'http_scheme'    { scheme_http }
         | 'ftp_scheme'     { scheme_ftp }
         ;
  
  host = 'id' '@' hostname             { host_info_login }
       | 'id' ':' 'id' '@' hostname    { host_info_login_password }
       | hostname                      { host_info }
       ;
       
  hostname = 'id' 'dot' 'id'/'dot'+                          { hostname_name }
           | 'value_literal' 'dot' 'value_literal'/'dot'+    { hostname_ip }
           ;
                
  port = ':' 'port_number'   { port }
       ;
       
  absolute_path = 'xpath_slash' path_step path_rest?  { absolute_path_rest }
                | 'xpath_slash'                       { absolute_path_slash }
                ;
                
  relative_uri = 'file://' path_step path_rest?             { relative_uri_step_rest }
               | 'file://' path_rest                        { relative_uri_rest }
               | 'file://' 'root_dir' path_step path_rest?  { relative_uri_rootdir }
               ;
            
  path_rest = 'xpath_slash' path_step path_rest   { path_rest_path }
            | 'xpath_slash' path_step             { path_rest_step }
            | 'xpath_slash'                       { path_rest_trailing_slash }
            ;     
       
  path_step = '.'                       { path_step_dot }
            | '..'                      { path_step_dotdot }
            | 'path_id'                 { path_step_id }
            | dollar_access             { path_step_dollar_access }
            ;
       
  uri_query = '?' uri_query_pair/'amp'+    { uri_query }
            ;      
            
  uri_query_pair = 'id' '=' 'id'  { uri_query_pair }
                 ;                         
        
  fragment = '#' 'id'     { fragment }
           ;
  